<a href="https://colab.research.google.com/github/PaulToronto/Math-and-Data-Science-Reference/blob/main/Cheat_Sheet_Solving_Systems_of_Linear_Equations_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sympy as sym
import scipy as sci

sym.init_printing(use_unicode=True)

# Solving Systems of Linear Equations with Python

$$
\begin{align}
4x_1 + 3x_2 + 2x_3 &= 25 \\
-2x_1 + 2x_2 + 3x_3 &= -10 \\
3x_1 - 5x_2 + 2x_3 &= -4
\end{align}
$$

## Inverse Method

$$
\begin{align}
Ax &= b \\
A^{-1}Ax &= A^{-1}b \\
Ix &= A^{-1}b \\
x &= A^{-1}b
\end{align}
$$

$$
A =
\left[
\begin{matrix}
4 & 3 & 2 \\
-2 & 2 & 3 \\
3 & -5 & 2
\end{matrix}
\right], 
x = 
\left[
\begin{matrix}
x_1 \\
x_2 \\
x_3
\end{matrix}
\right],
b = 
\left[
\begin{matrix}
25 \\
-10 \\
-4
\end{matrix}
\right]
$$

### Numpy

In [2]:
A = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
b = np.array([[25],
              [-10],
              [-4]])

np.linalg.inv(A).dot(b)

array([[ 5.],
       [ 3.],
       [-2.]])

In [3]:
np.linalg.inv(A) @ b

array([[ 5.],
       [ 3.],
       [-2.]])

### Sympy

In [4]:
symA = sym.Matrix(A)
symB = sym.Matrix(b)

symA**-1 * symB

⎡5 ⎤
⎢  ⎥
⎢3 ⎥
⎢  ⎥
⎣-2⎦

## Reduced Row Echelon Form

For this we need the augmented matrix, $G$

$$
A =
\left[
\begin{matrix}
4 & 3 & 2 & 25\\
-2 & 2 & 3 & -10 \\
3 & -5 & 2 & 4
\end{matrix}
\right]
$$

### Sympy

In [5]:
G = np.concatenate((A, b), axis=1)
G = sym.Matrix(G)

G.rref(pivots=False).col(-1)

⎡5 ⎤
⎢  ⎥
⎢3 ⎥
⎢  ⎥
⎣-2⎦

## `numpy.linalg.solve()`

In [6]:
np.linalg.solve(A, b)

array([[ 5.],
       [ 3.],
       [-2.]])

## `sympy.linsolve()`

In [7]:
x_1, x_2, x_3 = sym.symbols('x_1 x_2 x_3')
x_1, x_2, x_3

In [8]:
# the sig of the elements from the column
#  vector `b` has been changed
system = [4 * x_1 + 3 * x_2 + 2 * x_3 - 25,
          -2 * x_1 + 2 * x_2 + 3 * x_3 + 10,
          3 * x_1 - 5 * x_2 + 2 * x_3 + 4]
system

In [9]:
sym.linsolve(system, x_1, x_2, x_3)

In [10]:
sym.linsolve(G, x_1, x_2, x_3)

In [11]:
sym.linsolve((symA, symB), x_1, x_2, x_3)