<a href="https://colab.research.google.com/github/PaulToronto/Math-and-Data-Science-Reference/blob/main/Numpy_meshgrid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `numpy.meshgrid`

In [1]:
import numpy as np

In [2]:
x = [-4, -3, -2, -1, 0, 1, 2, 3, 4]
y = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
len(x), len(y), len(x) * len(y)

(9, 11, 99)

In [5]:
X, Y = np.meshgrid(x, y)

In [7]:
X.shape, X

((11, 9),
 array([[-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4]]))

In [8]:
Y.shape, Y

((11, 9),
 array([[-5, -5, -5, -5, -5, -5, -5, -5, -5],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5]]))

In [26]:
count = 0
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        count += 1
count

99

In [40]:
for i in range(X.shape[0]):
    for i in range(Y.shape[1]):
        print(X[x], Y[y])

[-4 -3 -2 -1  0  1  2  3  4] [-5 -5 -5 -5 -5 -5 -5 -5 -5]
[-4 -3 -2 -1  0  1  2  3  4] [-4 -4 -4 -4 -4 -4 -4 -4 -4]
[-4 -3 -2 -1  0  1  2  3  4] [-3 -3 -3 -3 -3 -3 -3 -3 -3]
[-4 -3 -2 -1  0  1  2  3  4] [-2 -2 -2 -2 -2 -2 -2 -2 -2]
[-4 -3 -2 -1  0  1  2  3  4] [-1 -1 -1 -1 -1 -1 -1 -1 -1]
[-4 -3 -2 -1  0  1  2  3  4] [0 0 0 0 0 0 0 0 0]
[-4 -3 -2 -1  0  1  2  3  4] [1 1 1 1 1 1 1 1 1]
[-4 -3 -2 -1  0  1  2  3  4] [2 2 2 2 2 2 2 2 2]
[-4 -3 -2 -1  0  1  2  3  4] [3 3 3 3 3 3 3 3 3]
[-4 -3 -2 -1  0  1  2  3  4] [-5 -5 -5 -5 -5 -5 -5 -5 -5]
[-4 -3 -2 -1  0  1  2  3  4] [-4 -4 -4 -4 -4 -4 -4 -4 -4]
[-4 -3 -2 -1  0  1  2  3  4] [-3 -3 -3 -3 -3 -3 -3 -3 -3]
[-4 -3 -2 -1  0  1  2  3  4] [-2 -2 -2 -2 -2 -2 -2 -2 -2]
[-4 -3 -2 -1  0  1  2  3  4] [-1 -1 -1 -1 -1 -1 -1 -1 -1]
[-4 -3 -2 -1  0  1  2  3  4] [0 0 0 0 0 0 0 0 0]
[-4 -3 -2 -1  0  1  2  3  4] [1 1 1 1 1 1 1 1 1]
[-4 -3 -2 -1  0  1  2  3  4] [2 2 2 2 2 2 2 2 2]
[-4 -3 -2 -1  0  1  2  3  4] [3 3 3 3 3 3 3 3 3]
[-4 -3 -2 -1  0  1  2  3  4]